import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AppBar from '@mui/material/AppBar'
import Container from '@mui/material/Container'
import Grid from '@mui/material/Grid'
import Link from '@mui/material/Link'
import DefaultButton from './components/default/Button'
import '../scss/index.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const itemsNav = [
  {text: 'Home', link: '/'},
  {text: 'Paises', link: '/paises'},
  {text: 'Formulario', link: '/'}
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) : JSX.Element{
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <AppBar 
          component="nav"
          className='navbar'
        >
          <Container>
            <Grid container spacing={2}>
              {itemsNav.map(item => (
              <Grid item xs={2}>
                <Link href={item.link}>
                  <DefaultButton text={item.text} color="#fafafa" />
                </Link>
              </Grid>
              ))}
            </Grid>
          </Container>
        </AppBar>
        <Container className='main-content'>
          {children}
        </Container>
      </body>
    </html>
  )
}
